name: active_deer
description: "A new Flutter project."

publish_to: "none"

version: 1.0.1

environment:
  sdk: ^3.9.0

dependencies:
  badges: ^3.1.2
  carousel_slider: ^5.1.1
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  curved_labeled_navigation_bar: ^2.0.6
  curved_navigation_bar: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.9.0
  dots_indicator: ^4.0.1
  flutter:
    sdk: flutter
  flutter_credit_card: ^4.1.0
  flutter_flavor: ^3.1.4
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^19.4.2
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.2.2
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.2.1
  get: ^4.7.2
  get_cli: ^1.9.1
  get_it: ^9.1.0
  get_storage: ^2.1.1
  image_picker: ^1.2.1
  intl: ^0.20.2
  latlong2: ^0.9.1
  lottie: ^3.3.2
  moyasar: ^2.1.1
  percent_indicator: ^4.2.5
  pinput: ^6.0.0
  pretty_dio_logger: ^1.4.0
  qr_flutter: ^4.1.0
  rename_app: ^1.6.5
  smooth_page_indicator: ^1.2.1
  table_calendar: ^3.2.0
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  wheel_picker: ^0.2.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  archive: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lotties/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900
